### ISSUE TITLE
amqp client

### ISSUE THREAD

**Issue by agborkowski** [kakserpom/phpdaemon#192]
Phpdeamon will be excellent to implement amqp protocol for broker and resolver message.

any ideas how to start implement async non blocking usage of this protocol ?

simplicity class over pecl amqp 
https://github.com/UnionOfRAD/li3_queue/blob/master/extensions/adapter/queue/AMQP.php

**Comment by agborkowski** [comment]
im considering it :), have u good accommodation !? :) :beers:

**Comment by kakserpom** [comment]
Yes I have. Are you going to implement this protocol in async way?

**Comment by agborkowski** [comment]
yeah ill try

**Comment by sashok1337** [comment]
Any results? 
I also need amqp client for my project :)

**Comment by hurdos** [comment]
@sashok1337 Added AMQP Clinet https://github.com/kakserpom/phpdaemon/blob/master/PHPDaemon/Clients/AMQP/README_RU.md
I think the ticket can be closed.

**Comment by sashok1337** [comment]
@hurdos thanx 👍 

Will test soon.
