### ISSUE TITLE
Protected __Construct Method Issues

### ISSUE THREAD

**Issue by woblit** [kakserpom/phpdaemon#201]
Getting an error when I try and start phpd -:

PHP Fatal error:  Call to protected PHPDaemon\Config\Parser::__construct() from context 'PHPDaemon\Config\Object' in /opt/phpdaemon/PHPDaemon/Config/Object.php on line 366

Noticed that the latest commit:
https://github.com/kakserpom/phpdaemon/commit/527c6f9bd5c8f9f4400509f628d5de0fcc1f97b1

Changed a number of files and the scope of the contruct method. This is a show stopper with the latest pull.

**Comment by kakserpom** [comment]
Thank you for the report, the problem shall be resolved in a few minutes.
