### ISSUE TITLE
HTTPS WebSocket

### ISSUE THREAD

**Issue by Falseclock** [kakserpom/phpdaemon#208]
Most of browsers disabled SSLv3, so websocket under HTTPS nor longer works.

https://github.com/kakserpom/phpdaemon/blob/master/PHPDaemon/BoundSocket/Generic.php#L270

should be changed to
```php
$this->ctx = new \EventSslContext(\EventSslContext::TLS_SERVER_METHOD, $params);
```
or new option to config should be added to choose cipher version.

**Comment by kakserpom** [comment]
Indeed, thank you, I've just committed this change. I think it's not necessary to choose cipher version, because TLS is so widely supported now.
