### ISSUE TITLE
Hangs when not in use for a long time

### ISSUE THREAD

**Issue by yefrem** [kakserpom/phpdaemon#209]
Hi. I've set up chat server using phpDaemon and WebSockets. It's not published yet so is only used by test users. I've noticed that if I don't connect and send any messages for about 2 days it hangs, clients cannot connect and phpd restart is needed. Is there any way to fix or track it?

**Comment by kakserpom** [comment]
What happens?

**Comment by yefrem** [comment]
uhm, I just described:) I have a WebSocket chat server. It works well, receives and sends messages and so on. But if nobody uses it for about two days it stops accepting clients (hangs). Browser console shows connection error and I should restart phpd to get it working again.

**Comment by kakserpom** [comment]
I was wondering what do you particularly mean by 'hanging'. Try to use max-idle 15m; to have workers restarted after being idle for at least 15 minutes (for instance).

**Comment by yefrem** [comment]
Tried max-idle but it didn't help, hanged again after several days of silence. Is there any other info I should provide?

**Comment by kakserpom** [comment]
What if you `pkill` workers instead of restart whole daemon?

**Comment by yefrem** [comment]
what should I actually check? wait until it hangs, then kill workers and see if they will be respawned?

**Comment by kakserpom** [comment]
Exactly so.

**Comment by yefrem** [comment]
So I contacted server admin and he did what you told me. Workers restarted but server still did not respond (client could not connect) until I did "phpd restart".

**Comment by kakserpom** [comment]
Quick fix: 'user root;' and remove 'privileged;' from the pool section in config.

**Comment by yefrem** [comment]
sadly didn't help :(

**Comment by yefrem** [comment]
Finally I discovered that the problem was caused by errors in my authorization process which caused client disconnection. So I'm going to close this issue. Only one little question: how do I get client IP address when using WebSockets?
