### ISSUE TITLE
ftok() failed - No such file or directory

### ISSUE THREAD

**Issue by aleksraiden** [kakserpom/phpdaemon#210]
Потестировал - происходит когда путь к pid-у относительный ( pidfile phpd.pid; ), если задать полностью, например, pidfile /var/run/phpd.pid;  - все ок

Полный вывод:

[PHPD] Warning: ftok(): ftok() failed - No such file or directory in /opt/www/fighterville.com/tmp/rtgengine/phpdaemon/PHPDaemon/Utils/ShmEntity.php:58
#1  PHPDaemon\Core\Daemon::errorHandler()
#2  ftok() called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/PHPDaemon/Utils/ShmEntity.php:58]
#3  PHPDaemon\Utils\ShmEntity->__construct() called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/PHPDaemon/Core/Daemon.php:425]
#4  PHPDaemon\Core\Daemon::init() called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/PHPDaemon/Core/Bootstrap.php:528]
#5  PHPDaemon\Core\Bootstrap::start() called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/PHPDaemon/Core/Bootstrap.php:317]
#6  PHPDaemon\Core\Bootstrap::init() called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/bin/phpd:72]
#7  include(/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/bin/phpd) called at [/opt/www/fighterville.com/tmp/rtgengine/phpdaemon/bin/sampleapp:5]

**Comment by kakserpom** [comment]
Поправил, теперь не будет Warning. Однако путь к pid-file всегда должен быть абсолютным.
