### ISSUE TITLE
SockJS\Examples\Simple и протоколы кроме WebSocket

### ISSUE THREAD

**Issue by aleksraiden** [kakserpom/phpdaemon#211]
Не смог добиться корректной работы дефолтного примера, если ограничить транспорты, исключив WebSocket. С ними все отлично.

Для примера, модифицируем SimpleRequest.php:

sock = new SockJS('http://'+document.domain+':8068/sockjs/', null, {protocols_whitelist: ['jsonp-polling']});

Так мы оставим только один протокол (jsonp-polling). После старта, идет запрос и он сразу закрывается, больше клиент не делает запросов никаких. При этом на сервере на первый взгляд все корректно, обработчик Methods\Jsonp.php отрабатывает.

Тестировал как на дефолной версии 0.3.4, так и на последней 1.0.3

**Comment by kakserpom** [comment]
Ммм, а у вас стоит Redis? ;-) Без него никак.

**Comment by aleksraiden** [comment]
Стоит, тестирую. Пришел к тому же выводу, анализируя исходники. Там есть еще два момент - наверное хорошо бы в лог писать этот момент, в второе - не очень пока разобрался где указать данные для подключения редиса - достаточно в конфиге поднять пул?

**Comment by kakserpom** [comment]
Пул даже поднимать не обязательно в конфиге, оно само поднимет и по дефолту будет соединяться к локальному редису. Если хочется странного, то да — поднять пул в конфиге. Если хочется поднять несколько SockJS-приложений с разными редисами, то можно указать в конфиге SockJS-приложения опцию redis-name "trololo"; и Pool:Clients\Redis:trololo {...странное...}

**Comment by aleksraiden** [comment]
да, в таком виде заработало, изначально была проблема с редисом за паролем. Если в конфигурации пула указать password 'aaa'; то в Clients\Redis\Connection.php  идет проверка именно значения пароля в виде $this->password, хотя мне кажется, что более правильно проверять значение с конфига - $this->pool->config->password->value.

**Comment by kakserpom** [comment]
tcp://user:pwd@127.0.0.1 — чем не устраивает?

**Comment by aleksraiden** [comment]
Хммм.. для редиса совсем неочевидный вариант (хотя да, работает). Но может более правильно будет все же привести к единому виду, как и с опцией select?

**Comment by kakserpom** [comment]
Это немного разные вещи. Select это глобальный идентификатор базы, как раз чтобы разделить namespace'ы глобально. Странно хотеть писать на одном сервере в одну базу, а на другом сервере в другую, более чем странно. Так что думаю лучше оставить всё как есть. Чтобы было очевидно можно дописать в документацию.

**Comment by aleksraiden** [comment]
Согласен, документации в этом месте не хватает :) Спасибо за помощь, уже в принципе, разобрался почти.

**Comment by kakserpom** [comment]
Если есть желание, возьмите и допишите что считаете нужным :) Буду признателен за Pull request.

**Comment by aleksraiden** [comment]
Так и делаю, пока несколько косметических правок, дальше буду вникать, по ходу дела и дополнять.
