### ISSUE TITLE
Ошибка при настроке сервера

### ISSUE THREAD

**Issue by trol929** [kakserpom/phpdaemon#225]
При команде sudo phpd start --verbose-tty=1
Появляется ошибка. в чем проблема?
PHP Parse error:  syntax error, unexpected '.', expecting ')' in /opt/phpdaemon/PHPDaemon/Core/Debug.php on line 69

**Comment by kakserpom** [comment]
PHP >= 5.6

**Comment by igorvish** [comment]
Which version of phpdaemon supports php5.4 or php5.5?

**Comment by trol929** [comment]
Меня тоже интересует какую версию phpdaemon надо использовать для php5.4 и где ее можно взять

**Comment by kakserpom** [comment]
igorvish: 5.6. Latest stable versions are always supported.

**Comment by kakserpom** [comment]
With PHP < 5.6 you can use phpDaemon older than Mar 2, 2016.

**Comment by trol929** [comment]
А где ее можно скачать?

**Comment by EzheG** [comment]
@trol929 https://github.com/kakserpom/phpdaemon/tree/fefc901eb740615aa6f6fc1ab53163ecbbcce58f

**Comment by kakserpom** [comment]
Почему бы не использовать 5.6?
