### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in PHPDaemon/Config/Object.php on line 19

### ISSUE THREAD

**Issue by sashok1337** [kakserpom/phpdaemon#289]
**What steps will reproduce the problem?**
install php 7.2.x
install phpDaemon

$phpd start

**What is the expected result?**
app is successfully launched

**What do you get instead?**
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in PHPDaemon/Config/Object.php on line 19

Object is reserved word since PHP 7.2.

**Comment by kakserpom** [comment]
The class must be renamed to _Object.
I am out on a trip, so feel free to send a Pull Request for this. 
Thank you.

**Comment by sashok1337** [comment]
@kakserpom pull request #290
