### ISSUE TITLE
Не запускается ExampleWebSocket

### ISSUE THREAD

**Issue by portnov87** [kakserpom/phpdaemon#74]
Добрый вечер. Не работает Пример ExampleWebSocket.
OS: CentOS 5
Установил как тут описано https://github.com/kakserpom/phpdaemon/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%28centos-%D0%B8-fedora-linux%29

Конфиг phpd.conf:

user nobody;
group nobody;

max-workers 20;
min-workers 20;
start-workers   20;
log-errors 1;
max-requests    1m;
max-idle    0;

ExampleWebSocket {
    privileged;
listen-port 8047;
listen tcp://188.165.118.170;
}
WebSocketServer {
    privileged;
listen tcp://188.165.118.170;
}
HTTP {
    privileged;
listen tcp://188.165.118.170;
 listen-port 82;
}
include conf.d/*.conf;

В клиенте пишу
                ws      : 'ws://188.165.118.170:8047/exampleApp',

Вот пример http://psypeople.com/testphpd.html
При нажатии на открыть пишет WebSocket closed.
Логи при этом пустые.
В чём причина не понимаю. Уже всё обыскал, всё пробывал что находил, ничего не помогает. омогите решить проблему. Что я не так делаю? Заранее спасибо.

**Comment by trol929** [comment]
У меня подобная проблема. Я не понял что должно быть в файле AppResolver

**Comment by dustingraham** [comment]
@trol929 Could you create a new issue with the exact error you're receiving. The error above is for a very old version of phpdaemon.
